Update README.md
capstone-cy-team-1/capstone-cy-team-1.github.io pull request #8
Opened 2023-03-28 16:04 UTC by 0xParth

Added DNS details

2023-03-29 16:52 UTC, ppsyllos33 reviewed
Looks Good

2023-03-31 01:55 UTC, realArcherL commented
Hey @0xParth good work resolving the conflicts, but I think after the merge, the main branch has overwritten your changes. Please update the branch and will merge it

2023-04-12 01:28 UTC, 0xParth reviewed
updates

2023-04-12 01:33 UTC, 0xParth commented
This one

2023-04-14 16:04 UTC, realArcherL requested changes

2023-04-14 16:04 UTC, realArcherL commented on README.md
>  Public Facing DNS Server: 34.121.172.3
Please remove the IP address from here. We are not adding it. Also, these are ephemeral, so there is no point sharing this.

2023-04-19 00:17 UTC, closed without merging